export interface Lesson {
  id: string;
  date: string;
  title: string;
  category: "arquitetura" | "segurança" | "pipeline" | "integracao" | "custo" | "processo";
  problem: string;
  solution: string;
  rule: string; // a regra derivada, curta e direta
  impact: "crítico" | "alto" | "médio";
  tags: string[];
}

export const LESSONS_DATA: Lesson[] = [
  {
    id: "L001",
    date: "2026-03-11",
    title: "RLS no Supabase — anon key não deve ter acesso de escrita",
    category: "segurança",
    problem: "Todas as tabelas do Supabase (tasks, agents, projects, knowledge) estavam abertas para escrita com a chave anon. Qualquer pessoa com a URL poderia alterar dados.",
    solution: "Habilitado RLS em todas as tabelas. Criadas políticas: anon = SELECT apenas; service_role = ALL. Dashboard usa anon para leitura; agentes usam service_role para escrita. Vercel recebeu SUPABASE_SERVICE_ROLE_KEY como env var.",
    rule: "Toda escrita no Supabase usa service_role. Anon key = somente leitura.",
    impact: "crítico",
    tags: ["supabase", "rls", "segurança", "dashboard"],
  },
  {
    id: "L002",
    date: "2026-03-11",
    title: "openclaw doctor --fix reseta o openclaw.json",
    category: "processo",
    problem: "Ao rodar `openclaw doctor --fix`, o arquivo openclaw.json é sobrescrito com valores padrão, perdendo configurações como modelo, compaction e hybrid search.",
    solution: "Sempre verificar e restaurar as chaves de configuração após qualquer `openclaw doctor --fix`.",
    rule: "Após `openclaw doctor --fix`: verificar model, compaction.flush, memory.hybridSearch.",
    impact: "alto",
    tags: ["openclaw", "configuração", "doctor"],
  },
  {
    id: "L003",
    date: "2026-03-10",
    title: "OmniHuman — endpoints corretos vs incorretos",
    category: "pipeline",
    problem: "Documentação e tutoriais mostram endpoints errados para o OmniHuman v1.5 no fal.ai, causando erros 404 e falhas silenciosas.",
    solution: "Upload de arquivo: `https://rest.alpha.fal.ai/storage/upload/initiate` (não fal.run/fal-ai/storage). Modelo: `https://queue.fal.run/fal-ai/bytedance/omnihuman/v1.5` (não fal.run/fal-ai/omnihuman-v1). Sync: `lipsync-1.9.0-beta` (não lipsync-2).",
    rule: "Usar `status_url` e `response_url` do response de fila diretamente, nunca hardcode caminhos.",
    impact: "alto",
    tags: ["omnihuman", "fal.ai", "pipeline-video", "lipsync"],
  },
  {
    id: "L004",
    date: "2026-03-10",
    title: "fal.ai — máximo 2 requests simultâneos",
    category: "custo",
    problem: "Rodar 7+ agentes em paralelo no fal.ai causa falhas silenciosas e desperdício de créditos.",
    solution: "Processar sempre em pares (máximo 2 requests paralelos). Pipeline omni_pipeline.sh implementado com controle de concorrência.",
    rule: "fal.ai: nunca mais de 2 requests simultâneos. Processar em pares.",
    impact: "alto",
    tags: ["fal.ai", "concorrência", "custo", "omnihuman"],
  },
  {
    id: "L005",
    date: "2026-03-10",
    title: "OmniHuman — limite de 28s de áudio por request",
    category: "pipeline",
    problem: "OmniHuman v1.5 rejeita áudios >= 30s. Tentativas com 60s falhavam silenciosamente.",
    solution: "Máximo 28s de áudio por request (margem de segurança). Áudio de 60s requer pipeline de 3 chunks com composição posterior.",
    rule: "OmniHuman: máx 28s/request. Vídeo longo = 3 chunks + composição.",
    impact: "alto",
    tags: ["omnihuman", "audio", "pipeline-video", "chunking"],
  },
  {
    id: "L006",
    date: "2026-03-09",
    title: "Meta Graph API — não aceita URLs do Google Drive",
    category: "integracao",
    problem: "Publicações no Instagram via Meta Graph API falhavam com URLs do Google Drive (redirecionamentos bloqueados).",
    solution: "Usar Imgur como CDN intermediário. Fazer upload da imagem no Imgur (Client-ID: 546c25a59c58ad7) e usar a URL direta do Imgur na chamada da API.",
    rule: "Instagram API: sempre usar Imgur como CDN. Drive URLs = bloqueadas.",
    impact: "alto",
    tags: ["instagram", "meta", "imgur", "graph-api"],
  },
  {
    id: "L007",
    date: "2026-03-09",
    title: "Gemini Imagen 4 — hex colors são interpretadas como texto",
    category: "pipeline",
    problem: "Prompts com códigos hex (#0A0A0A, #D4AF37) no Gemini Imagen 4 produziam imagens com texto literal em vez das cores.",
    solution: "Descrever cores em linguagem natural nos prompts: 'deep black background', 'golden tone', 'warm amber color'.",
    rule: "Imagen 4: nunca usar hex (#) em prompts. Descrever cores em palavras.",
    impact: "médio",
    tags: ["imagen4", "gemini", "prompt", "imagem"],
  },
  {
    id: "L008",
    date: "2026-03-08",
    title: "PDF gerado via Puppeteer/Chromium — não WeasyPrint",
    category: "pipeline",
    problem: "WeasyPrint v68 não renderiza CSS variables (--cor-primaria) nem fundos escuros (background: #0A0A0A). PDFs gerados ficavam com layout quebrado.",
    solution: "Usar Puppeteer/Chromium com `printBackground: true`. Produz PDFs idênticos ao browser, com CSS completo.",
    rule: "Geração de PDF: sempre Puppeteer/Chromium com printBackground:true.",
    impact: "alto",
    tags: ["pdf", "puppeteer", "weasyprint", "css"],
  },
  {
    id: "L009",
    date: "2026-03-11",
    title: "Agentes não veem tarefas aprovadas sem notificação ativa",
    category: "processo",
    problem: "Quando Yuri aprova uma tarefa no dashboard, o agente responsável não sabe — só descobre se consultar o Supabase no início da sessão (e apenas se a sessão for aberta depois da aprovação).",
    solution: "Criado `shared/notify-agents.sh` — cron a cada 15min que verifica `approval_status=approved AND status=backlog` e delega automaticamente para o agente via delegate.sh. Status muda para in_progress após notificação.",
    rule: "Aprovações no dashboard disparam notificação automática em até 15min via cron.",
    impact: "alto",
    tags: ["dashboard", "aprovação", "agentes", "cron", "supabase"],
  },
  {
    id: "L010",
    date: "2026-03-10",
    title: "Lip sync mais preciso com imagem bust (meio corpo), não full body",
    category: "pipeline",
    problem: "Vídeo full body tem rosto pequeno em proporção ao frame. O modelo de lipsync trabalha com menos pixels do rosto, resultando em sincronia labial imprecisa.",
    solution: "Usar imagem bust (rosto ocupando pelo menos 40% do frame) como entrada do lipsync. Para vídeo full body: composição em duas etapas — lipsync no bust, depois inserir num fundo full body.",
    rule: "Lipsync: sempre usar bust como base. Full body = composição separada.",
    impact: "médio",
    tags: ["lipsync", "avatar", "pipeline-video", "qualidade"],
  },
  {
    id: "L011",
    date: "2026-03-10",
    title: "Hedra Character-3 supera OmniHuman para avatares de produção",
    category: "arquitetura",
    problem: "OmniHuman exige chunking de áudio (máx 28s), tem concorrência limitada no fal.ai, gaze inconsistente e movimento pouco natural.",
    solution: "Migrar para Hedra Character-3: sem limite de duração, gaze mais natural, API simples, $0.10/vídeo de 60s, Creator plan $24/mês = 3.600 créditos.",
    rule: "Produção de avatar: Hedra Character-3 é o padrão. OmniHuman = legado.",
    impact: "alto",
    tags: ["hedra", "omnihuman", "avatar", "pipeline-video"],
  },
  {
    id: "L012",
    date: "2026-03-07",
    title: "Supabase como session-start protocol previne retrabalho",
    category: "processo",
    problem: "Agentes em sessões diferentes refaziam trabalho já concluído por não saberem o que outros tinham feito. Créditos desperdiçados.",
    solution: "Protocolo obrigatório: no início de cada sessão, consultar `tasks?status=in_progress` no Supabase antes de qualquer ação. Se houver task in_progress com seu agent_id, continue de onde parou.",
    rule: "Início de sessão: consultar Supabase tasks in_progress ANTES de qualquer ação.",
    impact: "alto",
    tags: ["supabase", "protocolo", "agentes", "retrabalho"],
  },
];

export const LESSON_CATEGORIES = [
  { id: "arquitetura", label: "Arquitetura",  color: "#D4AF37",  emoji: "🏛️" },
  { id: "segurança",   label: "Segurança",    color: "#EF4444",  emoji: "🔒" },
  { id: "pipeline",    label: "Pipeline",     color: "#8B5CF6",  emoji: "⚙️" },
  { id: "integracao",  label: "Integração",   color: "#06B6D4",  emoji: "🔗" },
  { id: "custo",       label: "Custo",        color: "#F59E0B",  emoji: "💰" },
  { id: "processo",    label: "Processo",     color: "#22C55E",  emoji: "📋" },
] as const;
