export interface SkillData {
  id: string;
  name: string;
  emoji: string;
  category: "desenvolvimento" | "produtividade" | "conteudo" | "infraestrutura" | "dados" | "comunicacao" | "ia";
  description: string;
  whenToUse: string[];
  whenNotToUse?: string[];
  howWeUse: string;
  agents: string[];
  requires?: string;
  homepage?: string;
  color: string;
  active: boolean; // se está em uso ativo no Panteão
}

export const SKILLS_DATA: SkillData[] = [
  {
    id: "coding-agent",
    name: "Coding Agent",
    emoji: "🤖",
    category: "desenvolvimento",
    description: "Delega tarefas de código para agentes especializados (Codex, Claude Code, Pi) rodando em background via processo. Permite que o agente principal continue trabalhando enquanto o código é gerado em paralelo.",
    whenToUse: [
      "Construir ou criar novas features e apps",
      "Revisar Pull Requests (spawna em pasta temporária)",
      "Refatorar grandes bases de código",
      "Tarefas iterativas de código que precisam explorar arquivos",
    ],
    whenNotToUse: [
      "Fixes simples de uma linha (use edit direto)",
      "Apenas leitura de código (use read tool)",
      "Qualquer trabalho dentro do workspace ~/clawd",
    ],
    howWeUse: "Hefesto usa para desenvolvimento do Dashboard, STM Contempla e integrações. Mariana usa para automações e scripts operacionais. Requer bash com suporte a pty:true.",
    agents: ["hefesto", "mariana"],
    color: "#B87333",
    active: true,
  },
  {
    id: "gog",
    name: "Google Workspace (gog)",
    emoji: "📧",
    category: "produtividade",
    description: "CLI completa para todo o ecossistema Google Workspace: Gmail, Google Calendar, Drive, Contacts, Sheets e Docs. Permite enviar emails, criar eventos, fazer upload de arquivos e manipular planilhas via linha de comando.",
    whenToUse: [
      "Enviar ou buscar emails do Gmail",
      "Criar, editar ou listar eventos no Calendar",
      "Fazer upload de arquivos no Drive",
      "Ler ou escrever em Google Sheets",
      "Exportar Google Docs para PDF ou HTML",
      "Gerenciar contatos do Google",
    ],
    howWeUse: "Hera usa para agenda e calendário do Yuri. Mariana usa para upload de entregas no Drive. Apollo usa para exportar documentos. Conta: yuri.moraes@stmgroup.com.br via Service Account.",
    agents: ["mariana", "hera", "apollo"],
    homepage: "https://gogcli.sh",
    color: "#4285F4",
    active: true,
  },
  {
    id: "healthcheck",
    name: "Healthcheck",
    emoji: "🛡️",
    category: "infraestrutura",
    description: "Auditoria de segurança e hardening para deployments OpenClaw. Verifica firewall, SSH, atualizações pendentes, postura de risco e versões dos serviços.",
    whenToUse: [
      "Auditorias de segurança do servidor",
      "Hardening de firewall e SSH",
      "Verificação de atualizações pendentes",
      "Revisão de exposição e risco do VPS",
    ],
    howWeUse: "Mariana usa periodicamente para verificar a saúde do VPS srv1404877. Hefesto usa antes de deploys críticos.",
    agents: ["mariana", "hefesto"],
    color: "#22C55E",
    active: true,
  },
  {
    id: "oracle",
    name: "Oracle",
    emoji: "🔮",
    category: "dados",
    description: "CLI para prompts avançados com bundling de arquivos e contexto. Permite enviar múltiplos arquivos como contexto para modelos de IA, gerenciar sessões e padrões de attachment complexos.",
    whenToUse: [
      "Análises com múltiplos arquivos de contexto",
      "Prompts que precisam de documentos de referência",
      "Sessões de análise persistentes",
      "Consultas com padrões de attachment complexos",
    ],
    howWeUse: "Atena usa para análises estratégicas com documentos. Apollo usa para produção com briefings. Afrodite usa para campanhas com contexto de marca.",
    agents: ["atena", "apollo", "afrodite", "hera", "ares"],
    homepage: "https://askoracle.dev",
    color: "#8B5CF6",
    active: true,
  },
  {
    id: "skill-creator",
    name: "Skill Creator",
    emoji: "🛠️",
    category: "infraestrutura",
    description: "Cria e atualiza AgentSkills para o OpenClaw. Permite projetar, estruturar e empacotar novas skills com scripts, referências e assets.",
    whenToUse: [
      "Criar uma nova skill customizada",
      "Atualizar skills existentes",
      "Empacotar scripts e assets como skill reutilizável",
    ],
    howWeUse: "Mariana e Hefesto usam quando identificamos uma automação recorrente que vale virar skill permanente.",
    agents: ["mariana", "hefesto"],
    color: "#F59E0B",
    active: true,
  },
  {
    id: "summarize",
    name: "Summarize",
    emoji: "📝",
    category: "conteudo",
    description: "Sumariza e extrai texto de URLs, podcasts, vídeos do YouTube e arquivos locais. Ótimo fallback para transcrever qualquer vídeo ou áudio.",
    whenToUse: [
      "Resumir artigos ou páginas web",
      "Transcrever vídeos do YouTube",
      "Extrair texto de podcasts",
      "Resumir arquivos PDF ou documentos locais",
    ],
    howWeUse: "Atena usa para pesquisa de mercado. Apollo usa para processar materiais de referência. Usado para processar cursos (ex: VTSD — 27 vídeos transcritos).",
    agents: ["atena", "apollo", "afrodite", "ares"],
    homepage: "https://summarize.sh",
    requires: "summarize CLI",
    color: "#06B6D4",
    active: true,
  },
  {
    id: "tmux",
    name: "Tmux",
    emoji: "🖥️",
    category: "infraestrutura",
    description: "Controla sessões tmux remotamente — envia teclas, captura output de painéis e automatiza CLIs interativas que precisam de TTY.",
    whenToUse: [
      "CLIs interativas que precisam de TTY",
      "Monitorar processos em background",
      "Enviar inputs para sessões de terminal ativas",
    ],
    howWeUse: "Hefesto usa para deploys e processos de build interativos. Mariana usa para monitorar scripts de longa duração.",
    agents: ["hefesto", "mariana"],
    requires: "tmux instalado",
    color: "#84CC16",
    active: true,
  },
  {
    id: "video-frames",
    name: "Video Frames",
    emoji: "🎬",
    category: "conteudo",
    description: "Extrai frames individuais ou clipes curtos de vídeos usando ffmpeg. Permite capturar thumbnails, cortar clipes ou extrair sequências de imagens.",
    whenToUse: [
      "Extrair frames de vídeos para thumbnails",
      "Cortar clipes curtos de vídeos maiores",
      "Pré-processar vídeos para pipeline de IA",
    ],
    howWeUse: "Usado no pipeline de produção de vídeo do Panteão Digital: QA visual, thumbnails e preparação de clipes para Instagram.",
    agents: ["apollo", "afrodite", "mariana"],
    homepage: "https://ffmpeg.org",
    requires: "ffmpeg",
    color: "#EF4444",
    active: true,
  },
  {
    id: "weather",
    name: "Weather",
    emoji: "🌤️",
    category: "dados",
    description: "Consulta clima atual e previsões via wttr.in ou Open-Meteo. Sem necessidade de API key. Suporta qualquer localidade do mundo.",
    whenToUse: [
      "Verificar clima atual em qualquer cidade",
      "Previsão para os próximos dias",
      "Clima antes de compromissos externos ou viagens",
    ],
    whenNotToUse: [
      "Dados históricos de clima",
      "Alertas meteorológicos severos",
    ],
    howWeUse: "Héstia usa antes de compromissos externos do Yuri e viagens. Sem configuração necessária.",
    agents: ["hestia"],
    homepage: "https://wttr.in/:help",
    requires: "curl",
    color: "#F97316",
    active: true,
  },
  {
    id: "notion",
    name: "Notion",
    emoji: "📓",
    category: "produtividade",
    description: "Integração com a API do Notion para criar e gerenciar páginas, databases e blocos. Permite criar tarefas, páginas de projeto e consultar bases de dados diretamente.",
    whenToUse: [
      "Criar ou atualizar páginas no Notion",
      "Inserir registros no DB de Projetos ou Tarefas",
      "Consultar databases do Notion",
      "Sincronizar informações com o Notion",
    ],
    howWeUse: "Hera usa na sincronização semanal Notion↔Trello (cron sexta 18h). Mariana usa para registrar entregas no DB Olimpo Tasks (ID: 31673897-662b-814c-a9d6-c64763d0824b).",
    agents: ["mariana", "hera"],
    homepage: "https://developers.notion.com",
    color: "#F5F5F5",
    active: true,
  },
  {
    id: "trello",
    name: "Trello",
    emoji: "📋",
    category: "produtividade",
    description: "Gerencia boards, listas e cards no Trello via REST API. Permite criar cards, mover entre listas e acompanhar o status operacional das verticais.",
    whenToUse: [
      "Criar cards de tarefas nas verticais",
      "Mover cards entre listas de status",
      "Consultar o board operacional Olimpo Operations",
    ],
    howWeUse: "Hera sincroniza com Notion toda sexta. Mariana registra entregas. Board principal: Olimpo Operations (ID: 69a42f673961bd3126fc0863). Boards por vertical também disponíveis.",
    agents: ["mariana", "hera"],
    homepage: "https://developer.atlassian.com/cloud/trello/rest/",
    color: "#0052CC",
    active: true,
  },
  {
    id: "github",
    name: "GitHub",
    emoji: "🐙",
    category: "desenvolvimento",
    description: "Operações no GitHub via `gh` CLI: issues, PRs, CI runs, code review e queries na API. Controla os repositórios da STM Group.",
    whenToUse: [
      "Verificar status de PR ou CI",
      "Criar ou comentar em issues",
      "Listar e filtrar PRs",
      "Ver logs de runs do GitHub Actions",
    ],
    whenNotToUse: [
      "Interações complexas que precisam da UI web",
      "Operações em massa (usar gh api com script)",
    ],
    howWeUse: "Hefesto usa para gerenciar os repos: panteon-dashboard, stmcapital-legal, agisales-microsaas. Token configurado nas env vars (expira 2026-06-06).",
    agents: ["hefesto", "mariana"],
    color: "#F5F5F5",
    active: true,
  },
  {
    id: "gemini",
    name: "Gemini CLI",
    emoji: "✦",
    category: "ia",
    description: "CLI do Gemini para Q&A, resumos e geração de conteúdo. Acesso direto aos modelos Gemini do Google incluindo Imagen 4 para geração de imagens.",
    whenToUse: [
      "Geração de imagens com Imagen 4",
      "Q&A rápido com modelos Gemini",
      "Geração de conteúdo com contexto",
    ],
    howWeUse: "Usado para geração de imagens das verticais (Imagen 4: imagen-4.0-fast-generate-001). API Key configurada em env vars. Regra: não usar hex colors (#) nos prompts.",
    agents: ["afrodite", "apollo", "mariana"],
    homepage: "https://ai.google.dev/",
    color: "#4285F4",
    active: true,
  },
  {
    id: "sag",
    name: "SAG (ElevenLabs TTS)",
    emoji: "🎙️",
    category: "conteudo",
    description: "Text-to-speech com ElevenLabs via interface estilo `say` do macOS. Gera áudio de alta qualidade com vozes realistas multilíngues para narração e vídeos.",
    whenToUse: [
      "Gerar áudio para roteiros de vídeo",
      "Narração de conteúdo educativo",
      "TTS de alta qualidade para reels e shorts",
    ],
    howWeUse: "Apollo usa para gerar o áudio dos vídeos do Panteão Digital. Modelo: eleven_multilingual_v2. Vozes mapeadas: Rachel (Mariana), Bella (Atena), Charlotte (Hera), Adam (Hefesto), Josh (Apollo). API Key configurada.",
    agents: ["apollo", "mariana"],
    homepage: "https://sag.sh",
    color: "#8B5CF6",
    active: true,
  },
  {
    id: "nano-banana-pro",
    name: "Nano Banana Pro",
    emoji: "🍌",
    category: "ia",
    description: "Geração e edição de imagens via Gemini 3 Pro Image (Nano Banana Pro). Alternativa ao Imagen 4 para casos que precisam de edição de imagens existentes.",
    whenToUse: [
      "Edição de imagens existentes com instruções em linguagem natural",
      "Geração de variações de imagens",
    ],
    whenNotToUse: [
      "API não responde consistentemente — use Gemini Imagen 4 como padrão",
      "Produção crítica sem fallback",
    ],
    howWeUse: "Disponível como fallback para Imagen 4. Historicamente instável no nosso ambiente — Imagen 4 é o padrão.",
    agents: ["afrodite", "apollo"],
    homepage: "https://ai.google.dev/",
    color: "#F59E0B",
    active: false,
  },
  {
    id: "nano-pdf",
    name: "Nano PDF",
    emoji: "📄",
    category: "conteudo",
    description: "Edita PDFs com instruções em linguagem natural via CLI. Permite modificar, anotar e transformar PDFs sem ferramentas gráficas.",
    whenToUse: [
      "Editar PDFs com linguagem natural",
      "Adicionar anotações ou modificar conteúdo",
      "Transformar estrutura de PDFs",
    ],
    howWeUse: "Disponível para Apollo ao finalizar e-books. Geração de PDFs definitivos usa Puppeteer/Chromium (printBackground:true) — mais confiável para documentos com CSS complexo.",
    agents: ["apollo", "hefesto"],
    requires: "nano-pdf CLI (pip)",
    color: "#EF4444",
    active: false,
  },
  {
    id: "xurl",
    name: "XURL (Twitter/X API)",
    emoji: "𝕏",
    category: "comunicacao",
    description: "CLI para autenticar e fazer requests à API v2 do X (Twitter). Permite postar tweets, responder, buscar posts, gerenciar seguidores, enviar DMs e fazer upload de mídia.",
    whenToUse: [
      "Postar tweets ou threads",
      "Responder ou citar posts",
      "Buscar posts por termo ou hashtag",
      "Upload de mídia para o X",
    ],
    howWeUse: "Disponível para Afrodite para eventual presença no X. Ainda não configurado com credenciais da STM Group.",
    agents: ["afrodite"],
    color: "#F5F5F5",
    active: false,
  },
];

export const SKILL_CATEGORIES = [
  { id: "desenvolvimento", label: "Desenvolvimento", color: "#B87333" },
  { id: "produtividade",   label: "Produtividade",   color: "#4285F4" },
  { id: "conteudo",        label: "Conteúdo",        color: "#06B6D4" },
  { id: "infraestrutura",  label: "Infraestrutura",  color: "#22C55E" },
  { id: "dados",           label: "Dados",           color: "#8B5CF6" },
  { id: "ia",              label: "IA & Geração",    color: "#F59E0B" },
  { id: "comunicacao",     label: "Comunicação",     color: "#EC4899" },
] as const;
